// Code generated by "stringer -type=EventError"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrPinTooShort-0]
	_ = x[ErrNoFace-1]
	_ = x[ErrTooManyFaces-2]
	_ = x[ErrFacePhotoNotTaken-3]
	_ = x[ErrInputDuringPhotoSession-4]
	_ = x[ErrAttendeeAlreadyExists-5]
}

const _EventError_name = "ErrPinTooShortErrNoFaceErrTooManyFacesErrFacePhotoNotTakenErrInputDuringPhotoSessionErrAttendeeAlreadyExists"

var _EventError_index = [...]uint8{0, 14, 23, 38, 58, 84, 108}

func (i EventError) String() string {
	if i >= EventError(len(_EventError_index)-1) {
		return "EventError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventError_name[_EventError_index[i]:_EventError_index[i+1]]
}
